// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let DynamodbAutoMarshaller = require("@aws/dynamodb-auto-marshaller");

function marshallValue(x) {
  return new DynamodbAutoMarshaller.Marshaller().marshallValue(x);
}

exports.marshallValue = marshallValue;
/* @aws/dynamodb-auto-marshaller Not a pure module */
