// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Brushless = require("brushless/src/Brushless.bs.js");
let DefaultMarshaller = require("./DefaultMarshaller.bs.js");

let register = Brushless.Register.make();

let rating = {
  TAG: "AttributeName",
  name: "rating"
};

let plot = {
  TAG: "AttributeName",
  name: "plot"
};

let examplePath_1 = [
  rating,
  {
    TAG: "ListIndex",
    index: 0
  },
  plot,
  {
    TAG: "ListIndex",
    index: 1
  },
  {
    TAG: "ListIndex",
    index: 1
  }
];

let examplePath = {
  TAG: "AttributePath",
  name: "info",
  subpath: examplePath_1
};

console.log(Brushless.AttributePath.toString(Brushless.AttributePath.fromString("info.rating[0].plot[1][1]")));

console.log(Brushless.AttributePath.toString(examplePath));

let year_1 = [{
    TAG: "ListIndex",
    index: 0
  }];

let year = {
  TAG: "AttributePath",
  name: "year",
  subpath: year_1
};

let title = {
  TAG: "AttributeName",
  name: "title"
};

let yearValue_0 = DefaultMarshaller.marshallValue(1992);

let yearValue = {
  TAG: "AttributeValue",
  value: yearValue_0,
  alias: "year"
};

let titleValue_0 = DefaultMarshaller.marshallValue("The Last of the Mohicans");

let titleValue = {
  TAG: "AttributeValue",
  value: titleValue_0,
  alias: "title"
};

let file = {
  TAG: "AttributeName",
  name: "file"
};

let minFileSize_0 = DefaultMarshaller.marshallValue(0);

let minFileSize = {
  TAG: "AttributeValue",
  value: minFileSize_0,
  alias: "minFileSize"
};

let exampleConditionExpression = Brushless.Condition.Overload.$amp$amp(Brushless.Condition.Overload.$amp$amp(Brushless.Condition.Overload.$eq$eq(year, yearValue), Brushless.Condition.Overload.$bang$eq(title, titleValue)), Brushless.Condition.Overload.$great({
  TAG: "Size",
  operand: file
}, minFileSize));

console.log(Brushless.Condition.build(exampleConditionExpression, register));

let exampleProjectionExpression = [
  {
    TAG: "AttributeName",
    name: "year"
  },
  {
    TAG: "AttributeName",
    name: "title"
  },
  {
    TAG: "AttributeName",
    name: "info"
  }
];

console.log(Brushless.Projection.build(exampleProjectionExpression, register));

let exampleKeyConditionExpression_pk = {
  name: {
    TAG: "AttributeName",
    name: "year"
  },
  value: {
    TAG: "AttributeValue",
    value: DefaultMarshaller.marshallValue(1992),
    alias: "year"
  }
};

let exampleKeyConditionExpression_sk = {
  TAG: "Comparison",
  name: {
    TAG: "AttributeName",
    name: "title"
  },
  comparator: "=",
  value: {
    TAG: "AttributeValue",
    value: DefaultMarshaller.marshallValue("The Last of the Mohicans"),
    alias: "title"
  }
};

let exampleKeyConditionExpression = {
  pk: exampleKeyConditionExpression_pk,
  sk: exampleKeyConditionExpression_sk
};

console.log(Brushless.KeyCondition.build(exampleKeyConditionExpression, register));

let exampleUpdateExpression_set = [
  [
    {
      TAG: "AttributeName",
      name: "rating"
    },
    {
      TAG: "AttributeValue",
      value: DefaultMarshaller.marshallValue(5),
      alias: "rating"
    }
  ],
  [
    {
      TAG: "AttributeName",
      name: "plot"
    },
    {
      TAG: "IfNotExists",
      identifier: {
        TAG: "AttributeName",
        name: "plot"
      },
      operand: {
        TAG: "AttributeValue",
        value: DefaultMarshaller.marshallValue("test"),
        alias: "plot"
      }
    }
  ]
];

let exampleUpdateExpression_remove = [{
    TAG: "AttributeName",
    name: "actors"
  }];

let exampleUpdateExpression_add = [[
    {
      TAG: "AttributeName",
      name: "actors"
    },
    {
      TAG: "AttributeValue",
      value: DefaultMarshaller.marshallValue([
        "Daniel Day-Lewis",
        "Madeleine Stowe"
      ]),
      alias: "actors"
    }
  ]];

let exampleUpdateExpression = {
  set: exampleUpdateExpression_set,
  remove: exampleUpdateExpression_remove,
  add: exampleUpdateExpression_add
};

console.log(Brushless.Update.build(exampleUpdateExpression, register));

console.log(register.names);

console.log(register.values);

let info = {
  TAG: "AttributeName",
  name: "info"
};

exports.register = register;
exports.info = info;
exports.rating = rating;
exports.plot = plot;
exports.examplePath = examplePath;
exports.year = year;
exports.title = title;
exports.yearValue = yearValue;
exports.titleValue = titleValue;
exports.file = file;
exports.minFileSize = minFileSize;
exports.exampleConditionExpression = exampleConditionExpression;
exports.exampleProjectionExpression = exampleProjectionExpression;
exports.exampleKeyConditionExpression = exampleKeyConditionExpression;
exports.exampleUpdateExpression = exampleUpdateExpression;
/* register Not a pure module */
