// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DynamodbAutoMarshaller = require("@aws/dynamodb-auto-marshaller");

var marshaller = new DynamodbAutoMarshaller.Marshaller();

function marshallValue(x) {
  return marshaller.marshallValue(x);
}

var DefaultMarshaller = {
  marshaller: marshaller,
  marshallValue: marshallValue
};

exports.DefaultMarshaller = DefaultMarshaller;
/* marshaller Not a pure module */
