// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Attribute from "./Attribute.res.js";

function make() {
  return {
          names: {},
          values: {}
        };
}

function add(register, element) {
  switch (element.TAG) {
    case "AttributePath" :
        [element._0].concat(element._1).forEach(function (sub) {
              if (sub.TAG !== "Name") {
                return ;
              }
              var name = sub._0;
              register.names[Attribute.toString({
                        TAG: "Name",
                        _0: name
                      })] = name;
            });
        break;
    case "Name" :
        register.names[Attribute.toString(element)] = element._0;
        break;
    case "AttributeValue" :
        register.values[Attribute.toString(element)] = element._0.value;
        break;
    
  }
  return element;
}

function addToString(register, element) {
  return Attribute.toString(add(register, element));
}

var Register = {
  make: make,
  add: add,
  addToString: addToString
};

function size(param_0) {
  return {
          TAG: "Size",
          _0: param_0
        };
}

function equals(param_0, param_1) {
  return {
          TAG: "Equals",
          _0: param_0,
          _1: param_1
        };
}

function notEquals(param_0, param_1) {
  return {
          TAG: "NotEquals",
          _0: param_0,
          _1: param_1
        };
}

function lessThan(param_0, param_1) {
  return {
          TAG: "LessThan",
          _0: param_0,
          _1: param_1
        };
}

function lessThanOrEqual(param_0, param_1) {
  return {
          TAG: "LessThanOrEqual",
          _0: param_0,
          _1: param_1
        };
}

function greaterThan(param_0, param_1) {
  return {
          TAG: "GreaterThan",
          _0: param_0,
          _1: param_1
        };
}

function greaterThanOrEqual(param_0, param_1) {
  return {
          TAG: "GreaterThanOrEqual",
          _0: param_0,
          _1: param_1
        };
}

function between(param_0, param_1) {
  return {
          TAG: "Between",
          _0: param_0,
          _1: param_1
        };
}

function inList(param_0, param_1) {
  return {
          TAG: "InList",
          _0: param_0,
          _1: param_1
        };
}

function and(param_0, param_1) {
  return {
          TAG: "And",
          _0: param_0,
          _1: param_1
        };
}

function or(param_0, param_1) {
  return {
          TAG: "Or",
          _0: param_0,
          _1: param_1
        };
}

function not(param_0) {
  return {
          TAG: "Not",
          _0: param_0
        };
}

function attributeExists(param_0) {
  return {
          TAG: "AttributeExists",
          _0: param_0
        };
}

function attributeNotExists(param_0) {
  return {
          TAG: "AttributeNotExists",
          _0: param_0
        };
}

function attributeType(param_0, param_1) {
  return {
          TAG: "AttributeType",
          _0: param_0,
          _1: param_1
        };
}

function beginsWith(param_0, param_1) {
  return {
          TAG: "BeginsWith",
          _0: param_0,
          _1: param_1
        };
}

function contains(param_0, param_1) {
  return {
          TAG: "Contains",
          _0: param_0,
          _1: param_1
        };
}

var Overload = {
  $amp$amp: and,
  $pipe$pipe: or,
  $bang: not,
  $eq$eq: equals,
  $bang$eq: notEquals,
  $less: lessThan,
  $less$eq: lessThanOrEqual,
  $great: greaterThan,
  $great$eq: greaterThanOrEqual
};

function build(condition, register) {
  var toString = function (condition) {
    switch (condition.TAG) {
      case "Equals" :
          return opString(condition._0) + " = " + opString(condition._1);
      case "NotEquals" :
          return opString(condition._0) + " <> " + opString(condition._1);
      case "LessThan" :
          return opString(condition._0) + " < " + opString(condition._1);
      case "LessThanOrEqual" :
          return opString(condition._0) + " <= " + opString(condition._1);
      case "GreaterThan" :
          return opString(condition._0) + " > " + opString(condition._1);
      case "GreaterThanOrEqual" :
          return opString(condition._0) + " >= " + opString(condition._1);
      case "Between" :
          var limits = condition._1;
          return opString(condition._0) + " BETWEEN " + opString(limits.lower) + " AND " + opString(limits.upper);
      case "InList" :
          return opString(condition._0) + " IN (" + condition._1.map(opString).join(", ") + ")";
      case "And" :
          return "(" + toString(condition._0) + ") AND (" + toString(condition._1) + ")";
      case "Or" :
          return "(" + toString(condition._0) + ") OR (" + toString(condition._1) + ")";
      case "Not" :
          return "NOT (" + toString(condition._0) + ")";
      case "AttributeExists" :
          return "attribute_exists(" + opString(condition._0) + "})";
      case "AttributeNotExists" :
          return "attribute_not_exists(" + opString(condition._0) + "})";
      case "AttributeType" :
          return "attribute_type(" + opString(condition._0) + "}, " + opString(condition._1) + ")";
      case "BeginsWith" :
          return "begins_with(" + opString(condition._0) + "}, " + opString(condition._1) + ")";
      case "Contains" :
          return "contains(" + opString(condition._0) + "}, " + opString(condition._1) + ")";
      
    }
  };
  var opString = function (operand) {
    switch (operand.TAG) {
      case "AttributePath" :
          return addToString(register, {
                      TAG: "AttributePath",
                      _0: operand._0,
                      _1: operand._1
                    });
      case "Name" :
          return addToString(register, {
                      TAG: "Name",
                      _0: operand._0
                    });
      case "AttributeValue" :
          return addToString(register, {
                      TAG: "AttributeValue",
                      _0: operand._0
                    });
      case "Size" :
          return "size(" + opString(operand._0) + "})";
      
    }
  };
  return toString(condition);
}

var Condition = {
  size: size,
  equals: equals,
  notEquals: notEquals,
  lessThan: lessThan,
  lessThanOrEqual: lessThanOrEqual,
  greaterThan: greaterThan,
  greaterThanOrEqual: greaterThanOrEqual,
  between: between,
  inList: inList,
  and: and,
  or: or,
  not: not,
  attributeExists: attributeExists,
  attributeNotExists: attributeNotExists,
  attributeType: attributeType,
  beginsWith: beginsWith,
  contains: contains,
  Overload: Overload,
  build: build
};

function build$1(projection, register) {
  return projection.map(function (x) {
                return addToString(register, x);
              }).join(", ");
}

var Projection = {
  build: build$1
};

function partitionKey(param_0, param_1) {
  return {
          TAG: "PartitionKey",
          _0: param_0,
          _1: param_1
        };
}

function equals$1(param_0, param_1) {
  return {
          TAG: "Equals",
          _0: param_0,
          _1: param_1
        };
}

function notEquals$1(param_0, param_1) {
  return {
          TAG: "NotEquals",
          _0: param_0,
          _1: param_1
        };
}

function lessThan$1(param_0, param_1) {
  return {
          TAG: "LessThan",
          _0: param_0,
          _1: param_1
        };
}

function lessThanOrEqual$1(param_0, param_1) {
  return {
          TAG: "LessThanOrEqual",
          _0: param_0,
          _1: param_1
        };
}

function greaterThan$1(param_0, param_1) {
  return {
          TAG: "GreaterThan",
          _0: param_0,
          _1: param_1
        };
}

function greaterThanOrEqual$1(param_0, param_1) {
  return {
          TAG: "GreaterThanOrEqual",
          _0: param_0,
          _1: param_1
        };
}

function between$1(param_0, param_1) {
  return {
          TAG: "Between",
          _0: param_0,
          _1: param_1
        };
}

function beginsWith$1(param_0, param_1) {
  return {
          TAG: "BeginsWith",
          _0: param_0,
          _1: param_1
        };
}

function skConditionToString(skCondition, register) {
  switch (skCondition.TAG) {
    case "Equals" :
        return " AND " + addToString(register, skCondition._0) + " = " + addToString(register, skCondition._1);
    case "NotEquals" :
        return " AND " + addToString(register, skCondition._0) + " <> " + addToString(register, skCondition._1);
    case "LessThan" :
        return " AND " + addToString(register, skCondition._0) + " < " + addToString(register, skCondition._1);
    case "LessThanOrEqual" :
        return " AND " + addToString(register, skCondition._0) + " <= " + addToString(register, skCondition._1);
    case "GreaterThan" :
        return " AND " + addToString(register, skCondition._0) + " > " + addToString(register, skCondition._1);
    case "GreaterThanOrEqual" :
        return " AND " + addToString(register, skCondition._0) + " >= " + addToString(register, skCondition._1);
    case "Between" :
        var limits = skCondition._1;
        return " AND " + addToString(register, skCondition._0) + " BETWEEN " + addToString(register, limits.lower) + " AND " + addToString(register, limits.upper);
    case "BeginsWith" :
        return " AND begins_with(" + addToString(register, skCondition._0) + ", " + addToString(register, skCondition._1) + ")";
    
  }
}

function pkConditionToString(param, register) {
  return addToString(register, param._0) + " = " + addToString(register, param._1);
}

function build$2(condition, register) {
  var skCondition = condition.sk;
  return pkConditionToString(condition.pk, register) + (
          skCondition !== undefined ? skConditionToString(skCondition, register) : ""
        );
}

var KeyCondition = {
  partitionKey: partitionKey,
  equals: equals$1,
  notEquals: notEquals$1,
  lessThan: lessThan$1,
  lessThanOrEqual: lessThanOrEqual$1,
  greaterThan: greaterThan$1,
  greaterThanOrEqual: greaterThanOrEqual$1,
  between: between$1,
  beginsWith: beginsWith$1,
  build: build$2
};

function attribute(param_0) {
  return {
          TAG: "Attribute",
          _0: param_0
        };
}

function listAppend(param_0) {
  return {
          TAG: "ListAppend",
          _0: param_0
        };
}

function ifNotExists(param_0) {
  return {
          TAG: "IfNotExists",
          _0: param_0
        };
}

function sum(param_0, param_1) {
  return {
          TAG: "Sum",
          _0: param_0,
          _1: param_1
        };
}

function sub(param_0, param_1) {
  return {
          TAG: "Sub",
          _0: param_0,
          _1: param_1
        };
}

function operandToString(operand, register) {
  switch (operand.TAG) {
    case "Attribute" :
        return addToString(register, operand._0);
    case "ListAppend" :
        var match = operand._0;
        return "list_append(" + operandToString(match.identifier, register) + ", " + operandToString(match.operand, register) + ")";
    case "IfNotExists" :
        var match$1 = operand._0;
        return "if_not_exists(" + operandToString(match$1.identifier, register) + ", " + operandToString(match$1.operand, register) + ")";
    case "Sum" :
        return operandToString(operand._0, register) + " + " + operandToString(operand._1, register);
    case "Sub" :
        return operandToString(operand._0, register) + " - " + operandToString(operand._1, register);
    
  }
}

function appendIfNotEmpty(acc, arr, tag, fn) {
  if (arr !== undefined && arr.length > 0) {
    return acc + tag + " " + arr.map(fn).join(", ") + " ";
  } else {
    return acc;
  }
}

function build$3(update, register) {
  return appendIfNotEmpty(appendIfNotEmpty(appendIfNotEmpty(appendIfNotEmpty("", update.add, "ADD", (function (param) {
                              return addToString(register, param[0]) + " " + addToString(register, param[1]);
                            })), update.delete, "DELETE", (function (param) {
                          return addToString(register, param[0]) + " " + addToString(register, param[1]);
                        })), update.set, "SET", (function (param) {
                      return addToString(register, param[0]) + " = " + operandToString(param[1], register);
                    })), update.remove, "REMOVE", (function (x) {
                  return addToString(register, x);
                })).trim();
}

var Update = {
  attribute: attribute,
  listAppend: listAppend,
  ifNotExists: ifNotExists,
  sum: sum,
  sub: sub,
  build: build$3
};

export {
  Register ,
  Condition ,
  Projection ,
  KeyCondition ,
  Update ,
}
/* Attribute Not a pure module */
